[package]
name = "live-server"
version = "0.1.1"
edition = "2021"
author = "Raunak Raj [bajrangcoders@gmail.com]"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"

